[package]
name = "itsanas-placement"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Deciding which nodes hold which chunks"

[dependencies]
blake3 = "1.8.7"
itsanas-crypto = { version = "0.1.0", path = "../itsanas-crypto" }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"

[lints]
workspace = true
